export const mockGrievances = [
  {
    id: 'GRV-2026-104',
    title: 'WiFi not working in Block C hostel',
    category: 'Infrastructure',
    description: 'Internet is completely down in Block C. Multiple students cannot submit assignments.',
    urgency: 4,
    sentiment: 'frustrated',
    department: 'IT Services',
    status: 'Pending',
    slaHours: 12,
    duplicateCount: 3,
    affectedStudents: 17,
    escalationRisk: 82,
    escalationRiskLevel: 'High',
    escalationReason: 'Hostel-wide outage with assignment deadlines approaching',
    estimatedResolutionDays: 1,
  },
  {
    id: 'GRV-2026-098',
    title: 'Course registration portal throwing 500 error',
    category: 'Academics',
    description: 'Cannot select elective courses, getting server error since yesterday. Deadline is today.',
    urgency: 5,
    sentiment: 'urgent',
    department: 'Academic Office',
    status: 'Pending',
    slaHours: 8,
    duplicateCount: 7,
    affectedStudents: 89,
    escalationRisk: 94,
    escalationRiskLevel: 'Critical',
    escalationReason: 'Mass issue affecting entire batch with an imminent deadline',
    estimatedResolutionDays: 1,
  },
  {
    id: 'GRV-2026-102',
    title: 'Water leakage in bathroom Block A Room 204',
    category: 'Hostel',
    description: 'Constant water dripping from ceiling. Floor is wet and slippery — safety hazard.',
    urgency: 5,
    sentiment: 'distressed',
    department: 'Maintenance',
    status: 'In Review',
    slaHours: 4,
    duplicateCount: 1,
    affectedStudents: 3,
    escalationRisk: 71,
    escalationRiskLevel: 'High',
    escalationReason: 'Safety hazard — wet floor poses injury risk',
    estimatedResolutionDays: 1,
  },
  {
    id: 'GRV-2026-088',
    title: 'Mess food quality severely deteriorated',
    category: 'Canteen',
    description: 'Food has been undercooked and unhygienic for the past 3 days. Several students unwell.',
    urgency: 4,
    sentiment: 'angry',
    department: 'Hostel Administration',
    status: 'In Review',
    slaHours: 24,
    duplicateCount: 5,
    affectedStudents: 120,
    escalationRisk: 68,
    escalationRiskLevel: 'Medium',
    escalationReason: 'Potential health concern with a large number of affected students',
    estimatedResolutionDays: 2,
  },
  {
    id: 'GRV-2026-091',
    title: 'Library overcrowded during exam week',
    category: 'Administration',
    description: 'No seats available in the library. Students sitting on the floor.',
    urgency: 2,
    sentiment: 'neutral',
    department: 'Library Admin',
    status: 'Resolved',
    slaHours: 48,
    duplicateCount: 2,
    affectedStudents: 45,
    escalationRisk: 23,
    escalationRiskLevel: 'Low',
    escalationReason: 'Recurring seasonal issue, manageable with scheduling',
    estimatedResolutionDays: 3,
  },
  {
    id: 'GRV-2026-081',
    title: 'AC not working in Computer Lab 3',
    category: 'Infrastructure',
    description: 'Temperature in computer lab is unbearable. Students unable to work for more than 20 minutes.',
    urgency: 3,
    sentiment: 'frustrated',
    department: 'Maintenance',
    status: 'Resolved',
    slaHours: 24,
    duplicateCount: 1,
    affectedStudents: 30,
    escalationRisk: 30,
    escalationRiskLevel: 'Low',
    escalationReason: 'Single-location issue, resolved within SLA',
    estimatedResolutionDays: 1,
  },
];

export const mockMaintenanceIssues = [
  {
    id: 'MNT-2026-201',
    location: 'Block C, Floor 2',
    issueType: 'Electrical',
    description: 'MCB trips every night around 9 PM. Happened 6 times this month.',
    severity: 4,
    priority: 'high',
    estimatedTime: '4 hours',
    status: 'Open',
    patternDetected: true,
    patternNote: '7 electrical complaints from Block C in 30 days',
    safetyRisk: true,
  },
  {
    id: 'MNT-2026-202',
    location: 'Block A, Corridor',
    issueType: 'Plumbing',
    description: 'Water cooler leaking onto the floor. Slippery surface.',
    severity: 4,
    priority: 'high',
    estimatedTime: '2 hours',
    status: 'Assigned',
    patternDetected: false,
    safetyRisk: true,
  },
  {
    id: 'MNT-2026-203',
    location: 'Block B, Room 101',
    issueType: 'Furniture',
    description: 'Study table leg broken. Cannot be used safely.',
    severity: 2,
    priority: 'low',
    estimatedTime: '1 day',
    status: 'Open',
    patternDetected: false,
    safetyRisk: false,
  },
];

export const mockLostItems = [
  {
    id: 'LF-2026-301',
    item: 'Black Lenovo Laptop',
    description: 'Lenovo ThinkPad, black carry sleeve, "Code Ninja" sticker on lid, charger included',
    location: 'Central Library — 2nd Floor',
    date: '2026-06-05',
    category: 'Electronics',
    caseId: 'LF-2026-301',
    recoveryProbability: 74,
    posterViews: 87,
    qrScans: 14,
    shares: 22,
    potentialMatches: 3,
  },
  {
    id: 'LF-2026-298',
    item: 'Blue Milton Water Bottle',
    description: 'Milton steel water bottle, blue color with a dent on the bottom, name written in marker',
    location: 'Main Canteen',
    date: '2026-06-05',
    category: 'Accessories',
    caseId: 'LF-2026-298',
    recoveryProbability: 61,
    posterViews: 43,
    qrScans: 6,
    shares: 11,
    potentialMatches: 1,
  },
];

export const mockFoundItems = [
  {
    id: 'LF-2026-F-401',
    item: 'Dark Blue Laptop',
    description: 'Lenovo laptop, dark blue / black, found with a carry sleeve near library exit',
    location: 'Library Exit Gate',
    date: '2026-06-06',
    category: 'Electronics',
  },
  {
    id: 'LF-2026-F-402',
    item: 'Metal Flask',
    description: 'Blue thermos flask, slight dent, no name on it',
    location: 'Library Reading Room',
    date: '2026-06-06',
    category: 'Accessories',
  },
];
